### ISSUE TITLE
Android Debug versus Release issue

### ISSUE THREAD

**Issue by bwilhelm** [kent-williams/hotspot-utility#11]
We updated our dev environment and can generate an APK file that works in debug mode, but when we try to create the release APK, the app Bluetooth hotspot detection no longer works. Is there a trick or special config we need for the release version for the Bluetooth functionality to work?

**Comment by DaxeshV** [comment]
> We updated our dev environment and can generate an APK file that works in debug mode, but when we try to create the release APK, the app Bluetooth hotspot detection no longer works. Is there a trick or special config we need for the release version for the Bluetooth functionality to work?

I am also facing same issue last 7 days.

**Comment by kent-williams** [comment]
It's likely a permissions problem. 

From the `flutter_blue` docs, the Bluetooth library used. https://pub.dev/documentation/flutter_blue/latest/

You may need to add the permissions below.

Android
In the android/app/src/main/AndroidManifest.xml let’s add:

```
	 <uses-permission android:name="android.permission.BLUETOOTH" />  
	 <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />  
	 <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>  
 <application
```

**Comment by piyushl85730** [comment]
> We updated our dev environment and can generate an APK file that works in debug mode, but when we try to create the release APK, the app Bluetooth hotspot detection no longer works. Is there a trick or special config we need for the release version for the Bluetooth functionality to work?

I also phase this issue. last 3 day to i am try to generate release apk but there something wrong in release apk. Also i have try all command instruction but not able to connect blutooth hostpot detection in release apk.

**Comment by DaxeshV** [comment]
> It's likely a permissions problem.
> 
> From the `flutter_blue` docs, the Bluetooth library used. https://pub.dev/documentation/flutter_blue/latest/
> 
> You may need to add the permissions below.
> 
> Android
> In the android/app/src/main/AndroidManifest.xml let’s add:
> 
> ```
> 	 <uses-permission android:name="android.permission.BLUETOOTH" />  
> 	 <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />  
> 	 <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>  
>  <application
> ```

Already added buddy! strange is app working fine for debug version. issue popup in signed apk.

**Comment by piyushl85730** [comment]
> It's likely a permissions problem.
> 
> From the `flutter_blue` docs, the Bluetooth library used. https://pub.dev/documentation/flutter_blue/latest/
> 
> You may need to add the permissions below.
> 
> Android
> In the android/app/src/main/AndroidManifest.xml let’s add:
> 
> ```
> 	 <uses-permission android:name="android.permission.BLUETOOTH" />  
> 	 <uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />  
> 	 <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>  
>  <application
> ```

Thank you for updates but i have already used this permission but still not work...

**Comment by bwilhelm** [comment]
To further clarify, in the release APK, the android device asks for permission to use the local location, so it appears to be registering the permission just fine, but the app does not ‘see’ the hotspot.

**Comment by bwilhelm** [comment]
It appears this is only an Android issue - we were able to create a build for iOS with all functionality working properly.

**Comment by kent-williams** [comment]
> It appears this is only an Android issue - we were able to create a build for iOS with all functionality working properly.

That's good to hear. Unfortunately I haven't experienced this issue on Android and I'm not sure what could be causing it.
I would suggest logging whatever you can at app startup and around any ble calls in hopes of catching the error.

**Comment by bwilhelm** [comment]
Thanks - we will try that and see what we can uncover and report back with any findings.

**Comment by bwilhelm** [comment]
We are still working on this issue. Here is the error that we are getting when testing the release APK after the user clicks the scan button and after allowing Bluetooth to access our location:

`2021-03-26 13:53:03.825 22201-22240/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(startScan, Field androidScanMode_ for b.b.a.s0 not found. Known fields are [private int b.b.a.s0.e, private b.a.b.b0$i b.b.a.s0.f, private boolean b.b.a.s0.g, private static final b.b.a.s0 b.b.a.s0.h, private static volatile b.a.b.a1 b.b.a.s0.i], java.lang.RuntimeException: Field androidScanMode_ for b.b.a.s0 not found. Known fields are [private int b.b.a.s0.e, private b.a.b.b0$i b.b.a.s0.f, private boolean b.b.a.s0.g, private static final b.b.a.s0 b.b.a.s0.h, private static volatile b.a.b.a1 b.b.a.s0.i]
        at b.a.b.v0.a(Unknown Source:72)
        at b.a.b.v0.a(Unknown Source:715)
        at b.a.b.v0.a(Unknown Source:12)
        at b.a.b.k0.a(Unknown Source:60)
        at b.a.b.k0.a(Unknown Source:49)
        at b.a.b.d1.a(Unknown Source:17)
        at b.a.b.d1.a(Unknown Source:4)
        at b.a.b.z$a.a(Unknown Source:9)
        at b.a.b.z$a.a(Unknown Source:4)
        at b.a.b.z$a.a(Unknown Source:0)
        at b.a.b.a$a.a(Unknown Source:2)
        at b.b.a.b.b(Unknown Source:10)
        at b.b.a.b.a(Unknown Source:1414)
        at c.a.c.a.j$a.a(Unknown Source:17)
        at io.flutter.embedding.engine.e.b.a(Unknown Source:57)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
    , null)
    #0      FlutterBlue.scan (package:flutter_blue/src/flutter_blue.dart:123)
    <asynchronous suspension>
2021-03-26 13:53:03.827 752-5080/? E/audio_hw_utils: audio_extn_utils_send_app_type_cfg: Failed to derive app_type for uc type : 0x1
2021-03-26 13:53:03.827 752-5080/? E/ACDB-LOADER: Error: ACDB AudProc vol returned = -19
2021-03-26 13:53:03.855 581-581/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2021-03-26 13:53:03.857 581-581/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2021-03-26 13:53:03.865 752-5080/? E/ACDB-LOADER: Error: ACDB AudProc vol returned = -19
2021-03-26 13:53:03.872 581-581/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2021-03-26 13:53:03.875 581-581/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2021-03-26 13:53:10.722 581-581/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2021-03-26 13:53:10.726 581-581/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2021-03-26 13:53:25.796 14125-22626/? E/memtrack: Couldn't load memtrack module
2021-03-26 13:53:41.897 18091-20662/? E/memtrack: Couldn't load memtrack module
2021-03-26 13:53:56.816 581-581/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2021-03-26 13:53:56.822 581-581/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2021-03-26 13:53:56.832 581-581/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2021-03-26 13:53:56.837 581-581/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2021-03-26 13:53:56.848 581-581/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2021-03-26 13:53:56.852 581-581/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2021-03-26 13:54:00.067 581-581/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2021-03-26 13:54:00.073 581-581/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2021-03-26 13:54:00.082 581-581/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2021-03-26 13:54:00.087 581-581/? E/libc: Access denied finding property "vendor.debug.egl.swapinterval"
2021-03-26 13:54:15.158 14125-19349/? E/SQLiteCastStore: Skip saving CastDeviceInfo: "Nearby device" (__cast_nearby___V_16e680b8-641b-4c28-9127-8428d9de5e71)
`

Any ideas?

**Comment by bwilhelm** [comment]
Hello - this thread and comment helped us resolve the issue:

https://github.com/pauldemarco/flutter_blue/issues/662#issuecomment-730831191

**Comment by kent-williams** [comment]
> Hello - this thread and comment helped us resolve the issue:
> 
> [pauldemarco/flutter_blue#662 (comment)](https://github.com/pauldemarco/flutter_blue/issues/662#issuecomment-730831191)

That's great to hear @bwilhelm! 

Would you mind closing the issue if that's all.
